name: HomePlugin
version: '${project.version}'
main: me.oyuncozucu.homeplugin.HomePlugin
api-version: 1.16
commands:
  sethome:
    description: ev noktasını belirler
  home:
    description: eve ışınlar
  delhome:
    description: ev noktasını siler